# Site settings
title: PlusReed
name: Reed # your name
email: reed@plusreed.com # your email address
description: >
    A Simple Jekyll Blog Theme. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://plusreed.github.io" # the base hostname & protocol for your site
twitter_username:  # your Twitter username
github_username: plusreed # your Github username
disqus_username: # your disqus username

google-analytics: UA-75034651-1 # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
